backend:
  name: git-gateway
  branch: main # Double check if your GitHub branch is 'main' or 'master'

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "inventory"
    label: "Shop Inventory"
    folder: "content/inventory"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["suit", "collection", "solar", "books"] }
      - { label: "Image", name: "image", widget: "image" }
